flask:
  build: Dockerfiles/python-flask-pymongo
  volumes:
    - app:/app
  links:
    - rethinkdb 
  ports:
    - "5000:5000"
  command: /usr/bin/python /app/app.py
rethinkdb:
  build: Dockerfiles/rethinkdb
  volumes:
    - data:/data
  ports:
    - "8080:8080"
    - "28015:28015"
    - "29015:29015"
